version: "3.3"

services: 
  nodeapp:
    build: .
    image: gcoooop/handlebar-node
    ports: 
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://betty:betty@cluster0-97nal.mongodb.net/handlebar_db?retryWrites=true&w=majority
    networks:
      backend:


networks:
  backend:
    driver: bridge